global: &default
  adapter: postgresql
  pool: <%= ENV.fetch("DATABASE_POOL", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
